### ISSUE TITLE
output does not match

### ISSUE THREAD

**Issue by shantanuo** [hellohaptik/spello#4]
I used this code to test spell model.

```
from spello.model import SpellCorrectionModel

sp = SpellCorrectionModel(language="en")
sp.load("en.pkl")
sp.spell_correct("i wnt to ply futbal")

{'original_text': 'i wnt to ply futbal',
 'spell_corrected_text': 'i want to ply futsal',
 'correction_dict': {'wnt': 'want', 'futbal': 'futsal'}}
```
The output that I got as mentioned above is a lot different than the one mentioned on github page.
https://github.com/hellohaptik/spello
```
{'original_text': 'i wnt to ply futbal',
 'spell_corrected_text': 'i want to play football',
 'correction_dict': {'wnt': 'want', 'ply': 'play', 'futbal': 'football'}
```
As you can see, the model does not suggest anything for "ply" and "futbal" correction is wrong.

What can be the reason behind this discrepancy?

**Comment by chiragjn** [comment]
Can you please tell us what model did you use? the lite one or the full one, it could be possible that since "ply" is a legit English word, the example might work with the lite model but not with the full model. This inability to correct already present words (but contextually incorrect) is mentioned in the README

Thanks for pointing this out, we will revise the examples
